language: python
sudo: false

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/matplotlib

matrix:
  include:
    - python: 3.5

before_install:
  - "export DISPLAY=:99.0"
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH
  - conda config --set show_channel_urls True
  - conda config --set always_yes True

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  # Install heavy stuff with conda, for speed.
  - conda create -n testenv python=$TRAVIS_PYTHON_VERSION scipy numpy coverage scikit-image pip -c conda-forge
  - source activate testenv
  - pip install -r requirements.txt
  - pip install pytest codecov pytest-cov
  - python setup.py install
  # Need to clean the python build directory (and other cruft) or pytest is
  # going to find the build directory and get confused why there are two sets
  # of every test file
  - git clean -xfd

script:
  - python run_tests.py

after_success:
  - coverage report -m
